name: zhixing-homepage
channels:
  - conda-forge
  - defaults
dependencies:
  - python ~=3.11.0

  # Framework dependencies
  - quarto
  - jupyter

  # Self-dependencies (e.g. I've written code that uses these in a document)
  - matplotlib-base ~=3.7.0
  - cartopy ~=0.21.1
